apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-app
  description: An example of a Backstage application.
  # Example for optional annotations
  # annotations:
    # github.com/project-slug: backstage/backstage
    # backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ustore-cert-service
  description: cert-based auth service
  tags:
    - go
spec:
  type: service
  lifecycle: production